# Generated by Django 4.2.3 on 2023-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
